### ISSUE TITLE
Klassviz master branch depends on bundle no longer provided by pragmatics master branch

### ISSUE THREAD

**Issue by aronlurie** [OpenKieler/klassviz#7]
In the MANIFEST of de.cau.cs.kieler.klassviz, there is a require-bundle of de.cau.cs.kieler.kiml, which is not in the plugins folder of the master branch of [pragmatics](https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse)

**Comment by le-cds** [comment]
We are currently migrating to the "new" Eclipse Layout Kernel project, which is what KIML used to be. After we have finished being hard at work there, we will update Klassviz to the new version.

klassviz should work with older releases of KIELER Pragmatics.

**Comment by livingjw** [comment]
Two years have passed and still missing de.cau.cs.kieler.kiml??

**Comment by le-cds** [comment]
Well, the other projects (KieSL, DebuKViz, and EcoreViz) have recently been updated (to a greater or lesser extent), but I did not have enough time available to update KlassViz as well since there's more work that needs to be done there (we need to move the project to a new Xtext version). It's still on the agenda.

**Comment by le-cds** [comment]
It has only taken us a good one-and-a-half years, but it's finally back up and running again.
